In [3]:
import pandas as pd
df = pd.read_csv(r'D:\python\PythonNangCao\Vietnam_COVID-19_patient.csv')
print(df)

        ID Gender   Age Nationality Detection Location Treatment Location  \
0      BN1      M  66.0       China   Ho Chi Minh City   Ho Chi Minh City
1      BN2      M  28.0       China   Ho Chi Minh City   Ho Chi Minh City
2      BN3      F  25.0     Vietnam          Thanh Hoa          Thanh Hoa
3      BN4      M  29.0     Vietnam          Vinh Phuc          Vinh Phuc
4      BN5      F  23.0     Vietnam          Vinh Phuc          Vinh Phuc
..     ...    ...   ...         ...                ...                ...
283  BN284      F  30.0     Vietnam            Can Tho            Can Tho
284  BN285      F  30.0     Vietnam            Can Tho            Can Tho
285  BN286      F  23.0     Vietnam            Can Tho            Can Tho
286  BN287      M  28.0     Vietnam            Can Tho            Can Tho
287  BN288      F  32.0     Vietnam            Can Tho            Can Tho

                                              Hospital Confirmed Date  \
0                                    Bệnh viện Chợ Rẫy        1/23/20
1                                    Bệnh viện Chợ Rẫy        1/23/20
2                     Bệnh viện đa khoa tỉnh Thanh Hóa        1/30/20
3    Bệnh viện Bệnh Nhiệt đới Trung Ương (cơ sở Đôn...        1/30/20
4        Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2)        1/30/20
..                                                 ...            ...
283                         Bệnh viện Đa khoa Bạc Liêu         5/7/20
284                         Bệnh viện Đa khoa Bạc Liêu         5/7/20
285                         Bệnh viện Đa khoa Bạc Liêu         5/7/20
286                         Bệnh viện Đa khoa Bạc Liêu         5/7/20
287                         Bệnh viện Đa khoa Bạc Liêu         5/7/20

     Travel History        Travel Country  ...            Discharged Date  \
0                 1          Wuhan(China)  ...                    2/12/20
1                 0                   NaN  ...                     2/4/20
2                 1          Wuhan(China)  ...  (Feb 2020, no exact date)
3                 1          Wuhan(China)  ...                    2/18/20
4                 1          Wuhan(China)  ...                    2/10/20
..              ...                   ...  ...                        ...
283               1  United Arab Emirates  ...                        NaN
284               1  United Arab Emirates  ...                        NaN
285               1  United Arab Emirates  ...                        NaN
286               1  United Arab Emirates  ...                        NaN
287               1  United Arab Emirates  ...                        NaN

    Re-Infected Re-discharged  \
0           NaN           NaN
1           NaN           NaN
2           NaN           NaN
3           NaN           NaN
4           NaN           NaN
..          ...           ...
283         NaN           NaN
284         NaN           NaN
285         NaN           NaN
286         NaN           NaN
287         NaN           NaN

                                           Reference 1  \
0    https://vnexpress.net/dich-viem-phoi-corona/ha...
1                                                  NaN
2    https://vnexpress.net/dich-viem-phoi-corona/ba...
3    https://vnexpress.net/dich-viem-phoi-corona/ba...
4    https://vnexpress.net/dich-viem-phoi-corona/ba...
..                                                 ...
283  https://vnexpress.net/them-17-ca-duong-tinh-nc...
284  https://vnexpress.net/them-17-ca-duong-tinh-nc...
285  https://vnexpress.net/them-17-ca-duong-tinh-nc...
286  https://vnexpress.net/them-17-ca-duong-tinh-nc...
287  https://vnexpress.net/them-17-ca-duong-tinh-nc...

                                           Reference 2  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3    https://vnexpress.net/suc-khoe/hai-benh-nhan-c...
4                                                  NaN
..                                                 ...
283                                                NaN
284                                                NaN
285                                                NaN
286                                                NaN
287                                                NaN

                                           Reference 3 Reference 4  \
0                                                  NaN         NaN
1                                                  NaN         NaN
2                                                  NaN         NaN
3    https://bnews.vn/dich-do-virus-corona-them-2-b...         NaN
4                                                  NaN         NaN
..                                                 ...         ...
283                                                NaN         NaN
284                                                NaN         NaN
285                                                NaN         NaN
286                                                NaN         NaN
287                                                NaN         NaN

    Reference 5 Note Number of negative test before discharged
0           NaN  NaN                                       NaN
1           NaN  NaN                                       NaN
2           NaN  NaN                                       NaN
3           NaN  NaN                                       NaN
4           NaN  NaN                                       NaN
..          ...  ...                                       ...
283         NaN  NaN                                       NaN
284         NaN  NaN                                       NaN
285         NaN  NaN                                       NaN
286         NaN  NaN                                       NaN
287         NaN  NaN                                       NaN

[288 rows x 30 columns]

b

In [18]:
df[(df['Travel Country'] == 'Wuhan(China)') ]

,ID,Gender,Age,Nationality,Detection Location,Treatment Location,Hospital,Confirmed Date,Travel History,Travel Country,...,Discharged Date,Re-Infected,Re-discharged,Reference 1,Reference 2,Reference 3,Reference 4,Reference 5,Note,Number of negative test before discharged
0,BN1,M,66.0,China,Ho Chi Minh City,Ho Chi Minh City,Bệnh viện Chợ Rẫy,1/23/20,1,Wuhan(China),...,2/12/20,NaN,NaN,https://vnexpress.net/dich-viem-phoi-corona/ha...,NaN,NaN,NaN,NaN,NaN,NaN
2,BN3,F,25.0,Vietnam,Thanh Hoa,Thanh Hoa,Bệnh viện đa khoa tỉnh Thanh Hóa,1/30/20,1,Wuhan(China),...,"(Feb 2020, no exact date)",NaN,NaN,https://vnexpress.net/dich-viem-phoi-corona/ba...,NaN,NaN,NaN,NaN,NaN,NaN
3,BN4,M,29.0,Vietnam,Vinh Phuc,Vinh Phuc,Bệnh viện Bệnh Nhiệt đới Trung Ương (cơ sở Đôn...,1/30/20,1,Wuhan(China),...,2/18/20,NaN,NaN,https://vnexpress.net/dich-viem-phoi-corona/ba...,https://vnexpress.net/suc-khoe/hai-benh-nhan-c...,https://bnews.vn/dich-do-virus-corona-them-2-b...,NaN,NaN,NaN,NaN
4,BN5,F,23.0,Vietnam,Vinh Phuc,Vinh Phuc,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),1/30/20,1,Wuhan(China),...,2/10/20,NaN,NaN,https://vnexpress.net/dich-viem-phoi-corona/ba...,NaN,NaN,NaN,NaN,NaN,NaN
7,BN8,F,29.0,Vietnam,Vinh Phuc,Vinh Phuc,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2/3/20,1,Wuhan(China),...,2/10/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,BN9,M,30.0,Vietnam,Vinh Phuc,Vinh Phuc,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2/4/20,1,Wuhan(China),...,2/10/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,BN13,F,29.0,Vietnam,Vinh Phuc,Vinh Phuc,Trung tâm y tế huyện Tam Đảo,2/7/20,1,Wuhan(China),...,"(Feb 2020, no exact date)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df['Confirmed Date'] = pd.to_datetime(df['Confirmed Date'])
# Ví dụ: Tìm bệnh nhân từ ngày 23/01/2020 đến 30/01/2020
start_date = '2020-03-1'
end_date = '2020-03-14'

mask = (df['Confirmed Date'] >= start_date) & (df['Confirmed Date'] <= end_date)
df_trong_khoang = df.loc[mask]

# Hiển thị kết quả
df_trong_khoang

C:\Users\User\AppData\Local\Temp\ipykernel_11800\3683387840.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Confirmed Date'] = pd.to_datetime(df['Confirmed Date'])

,ID,Gender,Age,Nationality,Detection Location,Treatment Location,Hospital,Confirmed Date,Travel History,Travel Country,...,Discharged Date,Re-Infected,Re-discharged,Reference 1,Reference 2,Reference 3,Reference 4,Reference 5,Note,Number of negative test before discharged
16,BN17,F,26.0,Vietnam,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-06,1,"Europe (Italy, France, United Kingdom)",...,3/30/20,NaN,NaN,https://beta.vnexpress.net/benh-covid-19-xuat-...,NaN,NaN,NaN,NaN,NaN,NaN
17,BN18,M,27.0,Vietnam,Ninh Binh,Ninh Binh,Bệnh viện Đa khoa tỉnh Ninh Bình,2020-03-07,1,Korea (Daegu),...,3/20/20,NaN,NaN,https://vnexpress.net/suc-khoe/chang-trai-nhie...,NaN,NaN,NaN,NaN,"10 people in the same quarantine room, includi...",NaN
18,BN19,F,64.0,Vietnam,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-07,0,NaN,...,NaN,NaN,NaN,https://vnexpress.net/suc-khoe/ba-benh-nhan-co...,https://vov.vn/xa-hoi/them-7-benh-nhan-covid-1...,NaN,NaN,NaN,NaN,NaN
19,BN20,M,28.0,Vietnam,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-07,0,NaN,...,4/2/20,NaN,NaN,https://vnexpress.net/suc-khoe/them-11-benh-nh...,https://vov.vn/xa-hoi/them-7-benh-nhan-covid-1...,https://vnexpress.net/suc-khoe/lai-xe-cua-benh...,NaN,NaN,NaN,NaN
20,BN21,M,61.0,Vietnam,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-08,1,United Kingdom,...,4/7/20,NaN,NaN,https://vnexpress.net/suc-khoe/viet-nam-cong-b...,https://vnexpress.net/27-nguoi-khoi-covid-19-h...,NaN,NaN,NaN,NaN,NaN
21,BN22,M,60.0,United Kingdom,Quang Ninh,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-08,1,United Kingdom,...,3/27/20,4/12/20,NaN,https://vnexpress.net/suc-khoe/ba-benh-nhan-co...,https://vnexpress.net/benh-nhan-duong-tinh-tro...,NaN,NaN,NaN,NaN,NaN
22,BN23,M,66.0,United Kingdom,Quang Ninh,Quang Nam,Bệnh viện Đa khoa khu vực miền núi phía Bắc Qu...,2020-03-08,1,United Kingdom,...,3/27/20,NaN,NaN,https://vnexpress.net/suc-khoe/ba-benh-nhan-co...,NaN,NaN,NaN,NaN,NaN,NaN
23,BN24,M,58.0,United Kingdom,Quang Ninh,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-08,1,United Kingdom,...,3/30/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,BN25,F,70.0,United Kingdom,Quang Ninh,Da Nang,Bệnh viện Đà Nẵng,2020-03-08,1,United Kingdom,...,4/10/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,BN26,F,50.0,Ireland,Lao Cai,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-08,1,United Kingdom,...,4/10/20,NaN,NaN,NaN,https://vnexpress.net/9-nguoi-xuat-vien-tai-ha...,NaN,NaN,NaN,NaN,NaN
26,BN27,M,67.0,United Kingdom,Lao Cai,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-08,1,United Kingdom,...,3/30/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,BN28,M,74.0,United Kingdom,Da Nang,Da Nang,Bệnh viện Bệnh Nhiệt đới Trung Ương (cơ sở Đôn...,2020-03-08,1,United Kingdom,...,4/14/20,NaN,NaN,https://vnexpress.net/hai-benh-nhan-nang-duoc-...,https://beta.vnexpress.net/benh-nhan-covid-19-...,NaN,NaN,NaN,Information about patient ID(s) among many UK ...,NaN
28,BN29,M,58.0,United Kingdom,Da Nang,Da Nang,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-08,1,United Kingdom,...,4/7/20,NaN,NaN,NaN,https://vnexpress.net/27-nguoi-khoi-covid-19-h...,NaN,NaN,NaN,NaN,NaN
29,BN30,F,66.0,United Kingdom,Hue,Hue,Bệnh viện Trung ương Huế,2020-03-08,1,United Kingdom,...,"(Early April 2020, no exact date)",NaN,NaN,https://vnexpress.net/suc-khoe/ba-benh-nhan-co...,https://vnexpress.net/suc-khoe/hai-benh-nhan-o...,NaN,NaN,NaN,NaN,NaN
30,BN31,M,49.0,United Kingdom,Quang Nam,Quang Nam,Bệnh viện Trung ương Huế,2020-03-09,1,United Kingdom,...,4/7/20,NaN,NaN,https://vnexpress.net/suc-khoe/ba-benh-nhan-co...,https://vnexpress.net/suc-khoe/hai-benh-nhan-o...,https://vnexpress.net/27-nguoi-khoi-covid-19-h...,NaN,NaN,NaN,NaN
31,BN32,F,24.0,Vietnam,Ho Chi Minh City,Ho Chi Minh City,Bệnh viện Dã chiến Củ Chi,2020-03-10,1,United Kingdom,...,3/31/20,NaN,NaN,https://vnexpress.net/suc-khoe/benh-nhan-32-he...,https://vnexpress.net/suc-khoe/so-ca-nhiem-nco...,NaN,NaN,NaN,NaN,NaN
32,BN33,M,58.0,United Kingdom,Quang Nam,Hue,Bệnh viện Trung ương Huế,2020-03-10,1,United Kingdom,...,"(Early April 2020, no exact date)",NaN,NaN,https://vnexpress.net/suc-khoe/cong-bo-ca-nhie...,NaN,NaN,NaN,NaN,NaN,NaN
33,BN34,F,59.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-10,1,"USA (Transit in South Korea, Qatar)",...,4/3/20,NaN,NaN,https://beta.vnexpress.net/viet-nam-cong-bo-ca...,NaN,NaN,NaN,NaN,NaN,NaN
34,BN35,F,29.0,Vietnam,Da Nang,Da Nang,Bệnh viện Đà Nẵng,2020-03-11,0,NaN,...,3/27/20,NaN,NaN,https://vnexpress.net/suc-khoe/ba-benh-nhan-co...,https://vnexpress.net/suc-khoe/viet-nam-ghi-nh...,NaN,NaN,NaN,NaN,NaN
35,BN36,F,64.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-11,0,NaN,...,4/10/20,4/24/20,NaN,https://vnexpress.net/suc-khoe/ba-ca-nhiem-nco...,https://vnexpress.net/hai-benh-nhan-cuoi-o-bin...,https://vnexpress.net/benh-nhan-36-tai-duong-t...,NaN,NaN,NaN,NaN
36,BN37,F,37.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-11,0,NaN,...,4/3/20,NaN,NaN,https://vnexpress.net/suc-khoe/ba-ca-nhiem-nco...,NaN,NaN,NaN,NaN,NaN,NaN
37,BN38,F,28.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-11,0,NaN,...,4/3/20,NaN,NaN,https://vnexpress.net/suc-khoe/ba-ca-nhiem-nco...,NaN,NaN,NaN,NaN,NaN,NaN
38,BN39,M,25.0,Vietnam,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-12,0,NaN,...,3/30/20,NaN,NaN,https://vnexpress.net/suc-khoe/cong-bo-ca-nhie...,https://vnexpress.net/suc-khoe/27-benh-nhan-om...,NaN,NaN,NaN,NaN,NaN
39,BN40,F,2.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-12,0,NaN,...,4/3/20,NaN,NaN,https://thethaiger.com/vietnam/binh-thuan-them...,NaN,NaN,NaN,NaN,NaN,NaN
40,BN41,M,59.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-12,0,NaN,...,4/3/20,NaN,NaN,https://thethaiger.com/vietnam/binh-thuan-them...,NaN,NaN,NaN,NaN,NaN,NaN
41,BN42,M,28.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-12,0,NaN,...,4/3/20,NaN,NaN,https://thethaiger.com/vietnam/binh-thuan-them...,NaN,NaN,NaN,NaN,NaN,NaN
42,BN43,F,47.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-12,0,NaN,...,4/3/20,NaN,NaN,https://thethaiger.com/vietnam/binh-thuan-them...,NaN,NaN,NaN,NaN,NaN,NaN
43,BN44,M,13.0,Vietnam,Binh Thuan,Binh Thuan,Bệnh viện Đa khoa tỉnh Bình Thuận,2020-03-12,0,NaN,...,4/10/20,NaN,NaN,https://thethaiger.com/vietnam/binh-thuan-them...,https://vnexpress.net/hai-benh-nhan-cuoi-o-bin...,NaN,NaN,NaN,NaN,NaN
44,BN45,M,25.0,Vietnam,Ho Chi Minh City,Ho Chi Minh City,Bệnh viện Dã chiến Củ Chi,2020-03-13,0,NaN,...,"(Early April 2020, no exact date)",NaN,NaN,https://vnexpress.net/suc-khoe/nam-thanh-nien-...,NaN,NaN,NaN,NaN,NaN,NaN
45,BN46,F,30.0,Vietnam,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-13,1,United Kingdom,...,3/30/20,NaN,NaN,https://vnexpress.net/suc-khoe/cong-bo-ca-nhie...,NaN,NaN,NaN,NaN,NaN,NaN
46,BN47,F,43.0,Vietnam,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-13,0,NaN,...,3/30/20,NaN,NaN,https://vnexpress.net/suc-khoe/cong-bo-ca-nhie...,NaN,NaN,NaN,NaN,NaN,NaN
47,BN48,M,31.0,Vietnam,Ho Chi Minh City,Ho Chi Minh City,Bệnh viện dã chiến Củ Chi,2020-03-14,0,NaN,...,"(Early April 2020, no exact date)",NaN,NaN,https://vnexpress.net/suc-khoe/them-mot-nguoi-...,NaN,NaN,NaN,NaN,NaN,NaN
48,BN49,M,71.0,United Kingdom,Hue,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-14,1,United Kingdom,...,3/31/20,NaN,NaN,https://vnexpress.net/suc-khoe/them-mot-hanh-k...,https://vnexpress.net/suc-khoe/so-ca-nhiem-nco...,NaN,NaN,NaN,NaN,NaN
49,BN50,M,50.0,Vietnam,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-14,1,France,...,4/14/20,4/29/20,NaN,https://vnexpress.net/suc-khoe/them-4-nguoi-nh...,https://vnexpress.net/hai-benh-nhan-nang-duoc-...,https://vnexpress.net/them-hai-nguoi-tai-duong...,NaN,NaN,NaN,NaN
50,BN51,F,24.0,Vietnam,Hanoi,Hanoi,Bệnh viện Việt Nam Thuỵ Điển Uông Bí,2020-03-14,1,United Kingdom,...,4/16/20,NaN,NaN,https://vnexpress.net/suc-khoe/them-4-nguoi-nh...,https://vnexpress.net/benh-nhan-13-lan-xet-ngh...,NaN,NaN,NaN,negative after 13 times of testing,NaN
51,BN52,F,22.0,Vietnam,Quang Ninh,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-14,1,Europe,...,4/17/20,4/21/20,NaN,https://vnexpress.net/suc-khoe/them-4-nguoi-nh...,https://vnexpress.net/nuoi-cay-virus-tim-nguye...,NaN,NaN,NaN,NaN,NaN
52,BN53,M,53.0,Czechia,Ho Chi Minh City,Ho Chi Minh City,Bệnh viện Dã chiến Củ Chi,2020-03-14,1,Czech(Transit in Qatar),...,3/30/20,NaN,NaN,https://vnexpress.net/suc-khoe/them-4-nguoi-nh...,https://vnexpress.net/suc-khoe/benh-nhan-czech...,NaN,NaN,NaN,NaN,NaN

In [36]:
df['Confirmed Date'] = pd.to_datetime(df['Confirmed Date'])
start_date='2020-03-01'
end_date='2020-03-30'
df[(df['Nationality'] == 'USA') & (df['Travel History'] == 1) &  (df['Confirmed Date'] >= start_date) & (df['Confirmed Date'] <= end_date) ]

,ID,Gender,Age,Nationality,Detection Location,Treatment Location,Hospital,Confirmed Date,Travel History,Travel Country,...,Discharged Date,Re-Infected,Re-discharged,Reference 1,Reference 2,Reference 3,Reference 4,Reference 5,Note,Number of negative test before discharged
67,BN68,M,41.0,USA,Da Nang,Da Nang,Bệnh viện Đà Nẵng,2020-03-18,1,7 other countries - Singapore,...,4/3/20,NaN,NaN,https://vnexpress.net/suc-khoe/da-nang-ghi-nha...,NaN,NaN,NaN,NaN,NaN,NaN
82,BN83,F,50.0,USA,Ho Chi Minh City,Ho Chi Minh City,Bệnh viện Dã chiến Củ Chi,2020-03-19,1,Thailand - Turkey,...,4/4/20,NaN,NaN,https://vnexpress.net/suc-khoe/9-nguoi-nhiem-n...,https://vnexpress.net/suc-khoe/them-4-benh-nha...,NaN,NaN,NaN,NaN,NaN
118,BN119,M,29.0,USA,Ho Chi Minh City,Ho Chi Minh City,Bệnh viện Dã chiến Củ Chi,2020-03-23,1,Indonesia - Thailand,...,4/7/20,NaN,NaN,https://vnexpress.net/suc-khoe/tp-hcm-va-tay-n...,https://vnexpress.net/27-nguoi-khoi-covid-19-h...,NaN,NaN,NaN,NaN,NaN
186,BN187,M,30.0,USA,Hanoi,Hanoi,Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2),2020-03-29,1,USA,...,3/30/20,NaN,NaN,https://vnexpress.net/suc-khoe/so-ca-nhiem-nco...,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
soluong = df['Gender'].value_counts()

# 2. Hiển thị kết quả
print("Thống kê số lượng Nam/Nữ:")
print(soluong)

Thống kê số lượng Nam/Nữ:
Gender
F    158
M    130
Name: count, dtype: int64

In [38]:
# Thống kê số ca theo quốc tịch
nationality_stats = df['Nationality'].value_counts()

# Hiển thị kết quả
print(nationality_stats)

Nationality
Vietnam           237
United Kingdom     21
Brazil              6
USA                 5
Germany             4
France              4
South Africa        3
China               2
Ireland             1
Czechia             1
Latvia              1
Canada              1
Denmark             1
Sweden              1
Name: count, dtype: int64

In [39]:

stats_tinh_thanh = df['Detection Location'].value_counts()

print("Thống kê số ca nhiễm theo tỉnh thành phát hiện:")
print(stats_tinh_thanh)

Thống kê số ca nhiễm theo tỉnh thành phát hiện:
Detection Location
Hanoi               112
Ho Chi Minh City     56
Vinh Phuc            19
Can Tho              19
Ninh Binh            13
Binh Thuan            9
Quang Ninh            6
Da Nang               6
Dong Thap             4
Ha Tinh               4
Thanh Hoa             3
Quang Nam             3
Tra Vinh              3
Tay Ninh              3
Bac Giang             3
Bac Lieu              3
Ha Nam                3
Lao Cai               2
Hue                   2
Ninh Thuan            2
Hai Duong             2
Lai Chau              2
Thai Binh             2
Khanh Hoa             1
Bac Ninh              1
Ben Tre               1
Thai Nguyen           1
Hung Yen              1
Dong Nai              1
Ha Giang              1
Name: count, dtype: int64

In [ ]:
stats_benh_vien = df['Hospital'].value_counts()
print("Thống kê số lượng bệnh nhân tại các bệnh viện:")
print(stats_benh_vien)

Thống kê số lượng bệnh nhân tại các bệnh viện:
Hospital
Bệnh viện Bệnh nhiệt đới Trung Ương (cơ sở 2)             106
Bệnh viện Bệnh Nhiệt đới Trung Ương (cơ sở Đông Anh)       30
Bệnh viện Dã chiến Củ Chi                                  30
Bệnh viện Đa khoa Bạc Liêu                                 17
Bệnh viện Đa khoa tỉnh Ninh Bình                           11
Bệnh viện Đa khoa tỉnh Bình Thuận                          10
Bệnh viện Bệnh Nhiệt đới TP HCM                             7
Bệnh viện Đà Nẵng                                           5
Bệnh viện Điều trị Covid-19 Cần Giờ                         5
Bệnh viện Bệnh nhiệt đới TP HCM                             4
Trung tâm y tế huyện Bình Xuyên                             4
Bệnh viện Đa khoa Sa Đéc                                    4
Bệnh viện Trung ương Huế                                    3
Bệnh viện điều trị Covid-19 Cần Giờ                         3
Bệnh viện Đa khoa Cầu Treo tỉnh Hà Tĩnh                     3
Bệnh viện Đa khoa tỉnh Bạc Liêu                             3
Bệnh viện Chợ Rẫy                                           2
Bệnh viện dã chiến Củ Chi                                   2
Trung tâm y tế huyện Thanh Miện, tỉnh Hải Dương             2
Bệnh viện Bạch Mai                                          2
Bệnh viện điều trị COVID-19 Cần Giờ                         2
Bệnh viện Lao và Bệnh phổi Trà Vinh                         2
Bệnh viện Đa khoa Tây Ninh                                  2
Bệnh viện Lao và Bệnh phổi Cần Thơ                          2
?                                                           2
Bệnh viện Đa khoa tỉnh Hà Nam                               2
Bệnh viện đa khoa tỉnh Thanh Hóa                            1
Bệnh viện Bệnh nhiệt đới Khánh Hòa                          1
Trung tâm y tế huyện Tam Đảo                                1
Bệnh viện Nhi Trung ương                                    1
Bệnh viện Đa khoa khu vực miền núi phía Bắc Quảng Nam       1
Bệnh viện Việt Nam Thuỵ Điển Uông Bí                        1
Bệnh viện Đa khoa Trung ương Quảng Nam                      1
Bệnh viện Đa khoa tỉnh Ninh Thuận                           1
Khoa Bệnh nhiệt đới, Bệnh viện Đa khoa tỉnh Ninh Thuận      1
Bệnh viện Đa khoa tỉnh Bắc Ninh                             1
Bệnh viện Dã Chiến Củ Chi                                   1
Trung tâm Y tế huyện Bình Đại, tỉnh Bến Tre                 1
Bệnh viện Đa khoa Bỉm Sơn                                   1
Bệnh viện Lao và bệnh phổi Cần Thơ                          1
Bệnh viện Đa khoa Kim Sơn (Ninh Bình)                       1
Bệnh viện Đa khoa Lai Châu                                  1
Đại Từ, Thái Nguyên                                         1
Phòng khám Đa khoa Khu vực Cầu Yên, tỉnh Ninh Bình          1
Bệnh viện Phổi tỉnh Đồng Nai                                1
Bệnh viện Đa khoa tỉnh Tây Ninh                             1
Bệnh viện Thận Hà Nội                                       1
Bệnh viện Cầu Treo, Hà Tĩnh                                 1
Bệnh viện Đa khoa huyện Đồng Văn                            1
Name: count, dtype: int64

In [45]:
# Lọc dữ liệu
df_cho_ray = df[df['Hospital'] == 'Bệnh viện Chợ Rẫy']
df_cho_ray.to_csv('BenhVienChoRay.csv', index=False, encoding='utf-8-sig')

In [43]:
df['Confirmed Date'] = pd.to_datetime(df['Confirmed Date'])
start_date='2020-03-01'
end_date='2020-03-30'
dfloc=df[(df['Nationality'] != 'VietNam') & (df['Travel History'] == 1) &  (df['Confirmed Date'].between(start_date, end_date)) ]
dfloc.to_csv('Nguoowfinuocngoai.csv', index=False, encoding='utf-8-sig')

Bài2

In [5]:
jf= pd.read_json(r'D:\python\PythonNangCao\LazadaProductData (1).json')
jf

,p_brand,p_cate,p_image,p_mall,p_name,p_number_reviews,p_price,p_rate1star,p_rate2star,p_rate3star,p_rate4star,p_rate5star,p_rating,s_name,s_rating,s_response_rate,s_ship_ontime
0,Dell,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/ab973a529b50491bb63a...,Mall,Laptop Dell Inspiron 7400 14.5 inches IPS QHD ...,Không có đánh giá,31.490.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,DELL Official Retail Store,88%,100%,100%
1,HP,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/0fc9119358dc21cb9dcd...,Mall,Laptop HP ProBook 450 G8 2H0Y1PA (Core i7-1165...,Không có đánh giá,31.490.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,An Phát HP,94%,89%,100%
2,HP,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/1063855536ce9dfae5dc...,Mall,Laptop HP 14s-fq1080AU 4K0Z7PA (Ryzen 3-5300U ...,1 đánh giá,12.390.000 ₫,0.0,0.0,0.0,0.0,1.0,5.0,An Phát HP,94%,89%,100%
3,Dell,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/756f7f7aeb632324816e...,Non-Mall,"Brand New Dell Alienware M17 R4 - 17.3"" 4K UHD...",Không có đánh giá,23.000.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,GADGETSHUB PLC,,66%,100%
4,OnePlus,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/ec69d1bd94b9e41f3f37...,Non-Mall,Brand New OnePlus 9 Pro - 256GB - Morning Mist...,Không có đánh giá,8.000.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,GADGETSHUB PLC,,66%,100%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2485,OEM,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/be232c0e9a669187e807...,Non-Mall,"Túi đeo chéo bao tử thời trang, chống nước (Đe...",25 đánh giá,75.000 ₫,NaN,NaN,NaN,NaN,NaN,NaN,Túi Xách New 3,96%,100%,100%
2486,OEM,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/7/tui-deo-cheo-1-qua...,Non-Mall,Túi đeo chéo 1 QUAI thể thao du lịch chống nướ...,95 đánh giá,70.000 ₫,3.0,3.0,5.0,17.0,67.0,4.5,Pitishop,90%,100%,100%
2487,Shalla,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/d5aa2bebef39f4854b7f...,Non-Mall,Túi đeo chéo vải nam và nữ mini phản quang xan...,51 đánh giá,72.000 ₫,0.0,0.0,1.0,1.0,49.0,4.9,Shalla vali balo,95%,92%,100%
2488,No Brand,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/be2a8203991c7a8b7963...,Non-Mall,Túi đeo chéo nam Unisex phong cách Hàn Quốc tí...,12 đánh giá,173.420 ₫,0.0,0.0,0.0,0.0,12.0,5.0,9-Hope,96%,100%,100%
2489,BEE GEE,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/158bb59aed3ee02ed208...,Mall,( FREESHIP + MGG + QUÀ TẶNG + VIDEO ) Túi đeo ...,13 đánh giá,95.200 ₫,1.0,0.0,1.0,0.0,11.0,4.5,BEE GEE,94%,98%,100%

Index(['ID', 'Gender', 'Age', 'Nationality', 'Detection Location',
       'Treatment Location', 'Hospital', 'Confirmed Date', 'Travel History',
       'Travel Country', 'Travel Country, Correct', 'Source of Infection',
       'Relationship', 'Flight ID (Date)', 'Infection Cluster',
       'Health Condition When Confirmed',
       'Detail Symptoms When Confirmed (clean up)',
       'Detail Symptoms When Confirmed', 'Developing Symptoms',
       'Underlying Health Condition', 'Discharged Date', 'Re-Infected',
       'Re-discharged', 'Reference 1', 'Reference 2', 'Reference 3',
       'Reference 4', 'Reference 5', 'Note',
       'Number of negative test before discharged'],
      dtype='str')

In [6]:
maytinh= jf[jf['p_cate'] =='Máy vi tính & Laptop']
maytinh

,p_brand,p_cate,p_image,p_mall,p_name,p_number_reviews,p_price,p_rate1star,p_rate2star,p_rate3star,p_rate4star,p_rate5star,p_rating,s_name,s_rating,s_response_rate,s_ship_ontime
0,Dell,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/ab973a529b50491bb63a...,Mall,Laptop Dell Inspiron 7400 14.5 inches IPS QHD ...,Không có đánh giá,31.490.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,DELL Official Retail Store,88%,100%,100%
1,HP,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/0fc9119358dc21cb9dcd...,Mall,Laptop HP ProBook 450 G8 2H0Y1PA (Core i7-1165...,Không có đánh giá,31.490.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,An Phát HP,94%,89%,100%
2,HP,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/1063855536ce9dfae5dc...,Mall,Laptop HP 14s-fq1080AU 4K0Z7PA (Ryzen 3-5300U ...,1 đánh giá,12.390.000 ₫,0.0,0.0,0.0,0.0,1.0,5.0,An Phát HP,94%,89%,100%
3,Dell,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/756f7f7aeb632324816e...,Non-Mall,"Brand New Dell Alienware M17 R4 - 17.3"" 4K UHD...",Không có đánh giá,23.000.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,GADGETSHUB PLC,,66%,100%
4,OnePlus,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/ec69d1bd94b9e41f3f37...,Non-Mall,Brand New OnePlus 9 Pro - 256GB - Morning Mist...,Không có đánh giá,8.000.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,GADGETSHUB PLC,,66%,100%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,No Brand,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/2/may-tinh-dong-bo-d...,Non-Mall,[Trả góp 0%]Máy tính đồng bộ Dell Optiplex 701...,6 đánh giá,4.665.650 ₫,0.0,0.0,1.0,1.0,4.0,4.5,Máy Tính Bảo Ngọc,86%,Không đủ thông tin,100%
395,No Brand,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/7e6603ef45a5226dde41...,Non-Mall,Thùng Đồng Bộ Dell Optiplex 990 (Core i5 2400 ...,21 đánh giá,3.350.000 ₫,0.0,1.0,1.0,4.0,15.0,4.6,Máy Tính Bảo Ngọc,86%,Không đủ thông tin,100%
396,Intel,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/2ea467c4ec7c6361ad4c...,Non-Mall,[HCM]Bộ máy tính LGA2L19 màn hình 19 rộng có W...,1 đánh giá,2.720.000 ₫,NaN,NaN,NaN,NaN,NaN,NaN,Vi tính Lê Gia,88%,100%,100%
397,No Brand,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/725bb6356e0f4040eacc...,Non-Mall,Vỏ Case Xigmatek NYX Kèm 4 Fan LED 5 Màu M-ATX...,6 đánh giá,419.000 ₫,0.0,0.0,0.0,0.0,6.0,5.0,NVH COMPUTER,87%,97%,100%
398,Dell,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/ed5f05503458b3f1037a...,Non-Mall,Máy Tính Để Bàn Đồng Bộ Dell Optiplex (Core i3...,Không có đánh giá,2.150.000 ₫,0.0,0.0,0.0,0.0,0.0,0.0,THANH BÌNH COMPUTER VN,,Không đủ thông tin,100%

In [7]:
danhgia=jf[jf['p_rating'] > 4]
danhgia

,p_brand,p_cate,p_image,p_mall,p_name,p_number_reviews,p_price,p_rate1star,p_rate2star,p_rate3star,p_rate4star,p_rate5star,p_rating,s_name,s_rating,s_response_rate,s_ship_ontime
2,HP,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/1063855536ce9dfae5dc...,Mall,Laptop HP 14s-fq1080AU 4K0Z7PA (Ryzen 3-5300U ...,1 đánh giá,12.390.000 ₫,0.0,0.0,0.0,0.0,1.0,5.0,An Phát HP,94%,89%,100%
12,Toshiba,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/101319cd821e7c28bfb1...,Non-Mall,[Xả Hàng] Toshiba Dynabook R731 (Portege R830)...,45 đánh giá,3.280.000 ₫,1.0,0.0,0.0,2.0,42.0,4.9,LAJAPA- Laptop Nhật Bản,97%,100%,100%
50,Toshiba,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/101319cd821e7c28bfb1...,Non-Mall,[Xả Hàng] Toshiba Dynabook R731 (Portege R830)...,45 đánh giá,3.280.000 ₫,1.0,0.0,0.0,2.0,42.0,4.9,LAJAPA- Laptop Nhật Bản,97%,100%,100%
68,Laptop,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/b6b2204ef02cb59d51d0...,Non-Mall,[Trả góp 0%]Laptop Asus E402 N3050/2GB/500GB t...,13 đánh giá,5.299.000 ₫,1.0,2.0,0.0,0.0,10.0,4.2,Siêu Thị Điện tử Nhập Khẩu Ntech,74%,Không đủ thông tin,100%
84,Dell,Máy vi tính & Laptop,//vn-live-05.slatic.net/p/386c7c0cb5e336a43d8d...,Mall,Laptop Dell Vostro 3400 14 inches FHD (Intel /...,13 đánh giá,16.990.000 ₫,2.0,0.0,0.0,2.0,9.0,4.2,DELL Official Retail Store,88%,100%,100%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2484,CHENNY,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/8e5ee1c00e2c035c95c0...,Non-Mall,[HCM]Túi đeo chéo Messenger thời trang cao cấp...,108 đánh giá,46.400 ₫,2.0,0.0,1.0,4.0,101.0,4.9,Chennybag,96%,100%,100%
2486,OEM,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/7/tui-deo-cheo-1-qua...,Non-Mall,Túi đeo chéo 1 QUAI thể thao du lịch chống nướ...,95 đánh giá,70.000 ₫,3.0,3.0,5.0,17.0,67.0,4.5,Pitishop,90%,100%,100%
2487,Shalla,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/d5aa2bebef39f4854b7f...,Non-Mall,Túi đeo chéo vải nam và nữ mini phản quang xan...,51 đánh giá,72.000 ₫,0.0,0.0,1.0,1.0,49.0,4.9,Shalla vali balo,95%,92%,100%
2488,No Brand,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/be2a8203991c7a8b7963...,Non-Mall,Túi đeo chéo nam Unisex phong cách Hàn Quốc tí...,12 đánh giá,173.420 ₫,0.0,0.0,0.0,0.0,12.0,5.0,9-Hope,96%,100%,100%
2489,BEE GEE,Túi xách và Vali túi du lịch,//vn-live-05.slatic.net/p/158bb59aed3ee02ed208...,Mall,( FREESHIP + MGG + QUÀ TẶNG + VIDEO ) Túi đeo ...,13 đánh giá,95.200 ₫,1.0,0.0,1.0,0.0,11.0,4.5,BEE GEE,94%,98%,100%

C

In [8]:
count_by_cate = jf['p_cate'].value_counts()
print(count_by_cate)

p_cate
Máy ảnh & Máy bay camera        718
Thiết bị thông minh             440
Máy vi tính & Laptop            399
Màn hình & Máy in               240
Âm thanh                        199
Electronics Accessories         175
Giày dép & Quần áo nữ           120
Điện thoại & Máy tính bảng       80
Túi xách và Vali túi du lịch     79
TV & Video                       40
Name: count, dtype: int64

In [10]:
top_10_high_rating = jf.sort_values(by='p_rating', ascending=False).head(10)
print(top_10_high_rating[['p_name', 'p_rating']])

                                                 p_name  p_rating
2     Laptop HP 14s-fq1080AU 4K0Z7PA (Ryzen 3-5300U ...       5.0
1539  [ SIÊU PHẨM – XẢ KHO ] Đồng Hồ Thông Minh Seri...       5.0
1540  Đồng hồ thông minh Watch 6 Plus - W26+ Pro  Sm...       5.0
1543  [HCM]Đồng Hồ SmartWatch Giá Rẻ - Mua Ngay Đồng...       5.0
1548  [HCM]Đồng Hồ Thông Minh Amazfit Bip U Pro | Bả...       5.0
1507                     [HCM]MỰC DYE EPSON INKTEC- LÍT       5.0
1508  combo 5 chai mực đổ máy in canon 2900, hp 1020...       5.0
2430  Balo nữ Alice chất liệu vải canvas chống thấm ...       5.0
2435      Balo da nam nữ thương hiệu Three-box - BL3518       5.0
2437                  Balo Thời Trang Nữ Da Trơn- BL020       5.0

In [18]:
jf['p_number_reviews'] = jf['p_number_reviews'].str.replace('Không có đánh giá', '0')
jf['p_number_reviews'] = jf['p_number_reviews'].str.replace(r'[^\d]', '', regex=True).astype(int)
has_reviews = jf[jf['p_number_reviews'] > 0]
top_100_low_rating = has_reviews.sort_values(by='p_rating', ascending=True).head(100)
print(top_100_low_rating[['p_name', 'p_rating', 'p_number_reviews']])

                                                 p_name  p_rating  \
2374  [ SIÊU KHUYẾN MÃI ] BỘ CHÓ DÀI SLOPPY CỰC HOT ...       2.0
1863  [HCM]Máy Chơi Game Box Retro G1 SUP Plus 400 in 1       2.5
1793  [HCM]Máy Chơi Game Box Retro G1 SUP Plus 400 in 1       2.5
1947  [HCM]Máy Chơi Game Box Retro G1 SUP Plus 400 in 1       2.5
1187  Máy Quay Hồng Ngoại ORDRO AC3 Máy Quay Video 4...       3.0
...                                                 ...       ...
1822  Nút bắn chơi game FPS GameSir F5 Falcon mini/A...       4.2
1525  Đồng hồ thông minh Amazfit GTS 2 Mini - Hàng C...       4.2
1973  S7edge S8 8+ 9 9+ 10 10+ Note 7 8 9 10 PLUS S1...       4.2
1933  Meiying M1 Pro | Bộ chuyển đổi game chơi PUBG ...       4.2
1939  Nút bắn chơi game FPS GameSir F5 Falcon mini/A...       4.2

      p_number_reviews
2374                 1
1863                 2
1793                 2
1947                 2
1187                 1
...                ...
1822                 5
1525                 5
1973                40
1933                 5
1939                 5

[100 rows x 3 columns]

In [22]:
cols_to_fix = ['p_rate1star', 'p_rate2star', 'p_rate3star', 'p_rate4star', 'p_rate5star', 'p_rating']
jf[cols_to_fix] = jf[cols_to_fix].fillna(0)
jf['p_price'] = jf['p_price'].str.replace(r'[^\d]', '', regex=True).astype(float)
jf['p_number_reviews'] = jf['p_number_reviews'].str.replace('Không có đánh giá', '0')
jf['p_number_reviews'] = jf['p_number_reviews'].str.replace(r'[^\d]', '', regex=True).astype(int)
cols_rating = ['p_rate1star', 'p_rate2star', 'p_rate3star', 'p_rate4star', 'p_rate5star', 'p_rating']
jf[cols_rating] = jf[cols_rating].fillna(0)

AttributeError: Can only use .str accessor with string values, not floating

In [19]:
jf.to_json('LazadaProducts_Cleaned.json', orient='records', force_ascii=False, indent=4)

In [6]:
import pandas as pd
dt = pd.read_xml('D:\python\PythonNangCao\AnyConv.com__netflix_data (1).xml')

# Hiển thị ra màn hình
print(dt.head())

<>:2: SyntaxWarning: invalid escape sequence '\p'
<>:2: SyntaxWarning: invalid escape sequence '\p'
C:\Users\User\AppData\Local\Temp\ipykernel_10664\48761037.py:2: SyntaxWarning: invalid escape sequence '\p'
  dt = pd.read_xml('D:\python\PythonNangCao\AnyConv.com__netflix_data (1).xml')

   Colors  WindowHeight  WindowWidth  WindowTopX  WindowTopY ProtectStructure  \
0     NaN           NaN          NaN         NaN         NaN              NaN
1     NaN        9000.0      13860.0       240.0        75.0            False
2     NaN           NaN          NaN         NaN         NaN              NaN
3     NaN           NaN          NaN         NaN         NaN              NaN

  ProtectWindows  Style   Name  Table  WorksheetOptions
0            NaN    NaN    NaN    NaN               NaN
1          False    NaN    NaN    NaN               NaN
2            NaN    NaN    NaN    NaN               NaN
3            NaN    NaN  input    NaN               NaN

In [9]:
from lxml import etree

tree = etree.parse(r"D:\python\PythonNangCao\AnyConv.com__netflix_data (1).xml")

# 1. Các bộ phim (Movie) phát hành năm 2020
# Giả sử cấu trúc là <record><type>Movie</type><release_year>2020</release_year></record>
movies_2020 = tree.xpath("//record[type='Movie' and release_year='2020']")

# 2. TV Show sản xuất tại United States phát hành năm 2021
tv_shows_us_2021 = tree.xpath("//record[type='TV Show' and country='United States' and release_year='2021']")

In [10]:
# 1. Số bộ phim sản xuất tại United States vào năm 2009
count_us_2009 = len(dt[(dt['type'] == 'Movie') & (dt['country'] == 'United States') & (dt['release_year'] == 2009)])
print(f"Số phim US năm 2009: {count_us_2009}")

# 2. Số video clips được sản xuất theo các nước
stats_country = dt['country'].value_counts()
print(stats_country)

# 3. Các chương trình "TV Show" có từ 2 mùa trở lên
# Lưu ý: Cột duration của TV Show thường ghi là "2 Seasons", ta cần tách lấy số
tv_shows = dt[dt['type'] == 'TV Show'].copy()
# Tách lấy phần ố và chuyển sang kiểu int
tv_shows['seasons'] = tv_shows['duration'].str.extract('(\d+)').astype(int)
tv_2_seasons = tv_shows[tv_shows['seasons'] >= 2]
print(tv_2_seasons[['title', 'duration']])

<>:13: SyntaxWarning: invalid escape sequence '\d'
<>:13: SyntaxWarning: invalid escape sequence '\d'
C:\Users\User\AppData\Local\Temp\ipykernel_10664\3832263153.py:13: SyntaxWarning: invalid escape sequence '\d'
  tv_shows['seasons'] = tv_shows['duration'].str.extract('(\d+)').astype(int)
C:\Users\User\AppData\Local\Temp\ipykernel_10664\3832263153.py:13: SyntaxWarning: invalid escape sequence '\d'
  tv_shows['seasons'] = tv_shows['duration'].str.extract('(\d+)').astype(int)

KeyError: 'type'

In [14]:
movies = dt[dt['type'] == 'Movie'].copy()
movies['duration_num'] = movies['duration'].str.extract('(\d+)').astype(float)

short_movies = movies[movies['duration_num'] <= 120]

short_movies.to_xml('ShortVideo.xml', index=False, encoding='utf-8')
print("Đã xuất file ShortVideo.xml thành công!")

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\User\AppData\Local\Temp\ipykernel_10664\3393085376.py:2: SyntaxWarning: invalid escape sequence '\d'
  movies['duration_num'] = movies['duration'].str.extract('(\d+)').astype(float)
C:\Users\User\AppData\Local\Temp\ipykernel_10664\3393085376.py:2: SyntaxWarning: invalid escape sequence '\d'
  movies['duration_num'] = movies['duration'].str.extract('(\d+)').astype(float)

KeyError: 'type'